/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package docorganizer;

import org.apache.pdfbox.cos.COSDocument;
import org.apache.pdfbox.io.RandomAccessBufferedFileInputStream;
import org.apache.pdfbox.io.RandomAccessRead;
import org.apache.pdfbox.pdfparser.PDFParser;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;

public class App {

    public static void main(String[] args) {

        PDFTextStripper pdfStripper = null;
        PDDocument pdDoc = null;
        COSDocument cosDoc = null;
        File file = new File(args[0]);
        try {
            // PDFBox 2.0.8 require org.apache.pdfbox.io.RandomAccessRead
            // RandomAccessFile randomAccessFile = new RandomAccessFile(file, "r");
            // PDFParser parser = new PDFParser(randomAccessFile);
            PDFParser parser = new PDFParser(new RandomAccessBufferedFileInputStream(file));
            parser.parse();
            cosDoc = parser.getDocument();
            pdfStripper = new PDFTextStripper();
            pdDoc = new PDDocument(cosDoc);
            pdfStripper.setStartPage(1);
            pdfStripper.setEndPage(1);
            String parsedText = pdfStripper.getText(pdDoc);

            if (parsedText.contains("www.aum-inc.com")){
                file.lastModified();
            }
            else {
                System.out.println(parsedText);
            }
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private void renameFile(File file, String name){
        if (file.canWrite()){
            String newName = file.getName()+file.lastModified();
        }
        else{
            System.out.println("File is not writable");
        }
    }
}
